### ISSUE TITLE
re fimH typing not performed

### ISSUE THREAD

**Issue by bhclement** [nmquijada/tormes#26] opened 2020-09-07 08:13 UTC
Hello,

I am using Tormes 1.2 to type my E. coli genomes.

All the analyses were completed, e.g. resistance, statistics, point mutations, virulence ... etc. except fimH

When I looked at the log file:
========================================================
(tormes-1.2.0) [ctsui@cdc1n2 ST131_Tormes]$ less tormes.log 

                - Number of contigs in genome E55_S17: 92
                - Number of contigs in genome E59_S4: 104
                - Number of contigs in genome E64_S9: 115
                - Number of contigs in genome E70_S15: 142
                - Number of contigs in genome E82_S5: 104
                - Number of contigs in genome E85_S8: 118
                - Number of contigs in genome E87_S10: 145
                - Number of contigs in genome E97_S2: 76

Taxonomic identification started at: 2020-09-06 22:59

MLST started at: 2020-09-06 23:02

Antibiotic resistance and virulence genes search started at: 2020-09-06 23:02

Annotation started at: 2020-09-07 00:05
Serotyping started at: 2020-09-07 00:43

FimH typing started at: 2020-09-07 00:44
WARNING: FimH typing was not performed

Plasmid search started at: 2020-09-07 00:44

Point mutation search started at: 2020-09-07 00:44

Tormes report started at: 2020-09-07 00:50

TORMES pipeline finished at: 2020-09-07 00:51

--------------------------------------------
Why fimH typing not perform? Any reasons?

Thanks,
Clement

**Comment by nmquijada** [comment] 2020-09-07 10:06
Hi Clement,

Something might have failed with your FimTyper software. Let's try to make it work with one of your genomes. Could you please try to run the following command and post the output here (after activating tormes environment and by modifying the required PATHs)?

```
perl PATH/TO/fimtyper.pl -d PATH/TO/fimtyper-database -b PATH/TO/blast-binaries -i YOUR-GENOME.fasta -o OUTPUT -k 95.00 -l 0.80
```

If you have problems while getting all the software locations/paths, please just post the output of this command here (after activating tormes environment), ```which tormes``` , and I will give you all the locations.

Thanks,
Narciso

**Comment by bhclement** [comment] 2020-09-07 12:41
Hi Narciso, Thanks for your reply and advice.

the perl script returns with 
> Can't open perl script "PATH/TO/fimtyper.pl": No such file or directory
after typing which tormes, it returns:

~/.conda/envs/tormes-1.2.0/bin/tormes

best,
Clement

**Comment by bhclement** [comment] 2020-09-07 12:52
Are these the path?
(tormes-1.2.0) [ctsui@cdc1n2 parsnp]$ find ~/.conda/envs/tormes-1.2.0/ -name fimtyper*
/home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper
/home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl
/home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db

(tormes-1.2.0) [ctsui@cdc1n2 parsnp]$ find ~/.conda/envs/tormes-1.2.0/ -name blast*
/home/ctsui/.conda/envs/tormes-1.2.0/conda-meta/blast-2.10.1-pl526he19e7b1_1.json
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blast_formatter
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastdb_aliastool
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastdbcheck
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastdbcmd
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastp
/home/ctsui/.conda/envs/tormes-1.2.0/bin/blastx
/home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2/Bio/SearchIO/blast.pm
/home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2/Bio/SearchIO/blast_pull.pm
/home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2/Bio/SearchIO/blasttable.pm
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/__pycache__/blast_tab.cpython-36.pyc
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/__pycache__/blast_text.cpython-36.pyc
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/__pycache__/blast_xml.cpython-36.pyc
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_tab.py
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_text.py
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/Bio/SearchIO/BlastIO/blast_xml.py
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/sistr/src/blast_wrapper
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/cgecore/blaster
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/cgecore/blaster/__pycache__/blaster.cpython-36.pyc
/home/ctsui/.conda/envs/tormes-1.2.0/lib/python3.6/site-packages/cgecore/blaster/blaster.py
/home/ctsui/.conda/envs/tormes-1.2.0/share/easel/demotic/blast2profmark
/home/ctsui/.conda/envs/tormes-1.2.0/share/easel/demotic/blast2tbl
/home/ctsui/.conda/envs/tormes-1.2.0/db/blast

**Comment by bhclement** [comment] 2020-09-07 13:04
Hello,

Here's what I did. Does it help to resolve the problem?

$ perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn -i E111_S15_contigs.filter.fasta -o output -k 95.00 -l 0.80

Can't locate Try/Tiny/Retry.pm in @INC (you may need to install the Try::Tiny::Retry module) (@INC contains: /home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2 /home/ctsui/.conda/envs/tormes-1.2.0/lib/5.26.2/x86_64-linux-thread-multi /home/ctsui/.conda/envs/tormes-1.2.0/lib/5.26.2 .) at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 11.
BEGIN failed--compilation aborted at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 11.

thanks,

**Comment by nmquijada** [comment] 2020-09-07 14:15
Hi Clement,

Thanks for posting the outputs. The paths you wrote are correct. However you are missing some flags in your command, it should be:

```
perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl -d /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db -b /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn -i E111_S15_contigs.filter.fasta -o output -k 95.00 -l 0.80
```

However, the source of your problem is that you are missing on Perl package called "Try Tiny". There are severall ways to install it. Activate the tormes environment and then:
```
 conda install -c bioconda perl-try-tiny
```

Then, run the FimTyper command above and let me know if it worked.

**Comment by bhclement** [comment] 2020-09-07 17:05
Hi Narciso,

Thanks.
I installed Try Tiny following your command. But when I run the same FimTyper command. The same error message appeared (I already conda deactivate and activate Tormes again after the installation):

 ### $ perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl -d /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db -b /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn -i E111_S15_contigs.filter.fasta -o output -k 95.00 -l 0.80
 Can't locate Try/Tiny/Retry.pm in @INC (you may need to install the Try::Tiny::Retry module) (@INC contains: /home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ctsui/.conda/envs/tormes-1.2.0/lib/site_perl/5.26.2 /home/ctsui/.conda/envs/tormes-1.2.0/lib/5.26.2/x86_64-linux-thread-multi /home/ctsui/.conda/envs/tormes-1.2.0/lib/5.26.2 .) at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 11.
BEGIN failed--compilation aborted at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 11.

**Comment by nmquijada** [comment] 2020-09-08 07:10
Hi Clement,

The installation via conda failed, let's try with CPAN. Please activate tormes environment and type:
```
conda install -c bioconda perl-app-cpanminus
cpanm Try::Tiny::Retry --force
```
And then, if the installation run without errors, run the FimTyper command again.

**Comment by bhclement** [comment] 2020-09-08 11:17
Hi Narciso,

Thanks. Try: tiny is installed. But when I run the FimTyper command, a new issue appears:

$ perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl -d /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db -b /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn -i E111_S15_contigs.filter.fasta -o E111_output -k 95.00 -l 0.80

sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin/blastn/bin/makeblastdb: Not a directory
Error! Could not build blast database at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 1052.

this is related to blast db

regards,

**Comment by nmquijada** [comment] 2020-09-08 11:23
Hi Clement,
We are getting closer! 
Sorry I made a mistake when posting you the FimTyper command. Flag -b has to target the blast binaries directory, not the blastn itself. So the command should be:
```
perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl -d /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db -b /home/ctsui/.conda/envs/tormes-1.2.0/bin/ -i E111_S15_contigs.filter.fasta -o E111_output -k 95.00 -l 0.80
```
Let me know!

**Comment by bhclement** [comment] 2020-09-08 15:12
Hello,

Sorry. it does not work. the error message is the same.

sh: /home/ctsui/.conda/envs/tormes-1.2.0/bin//bin/makeblastdb: No such file or directory
Error! Could not build blast database at /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl line 1052.

somehow the blast package is not right! or the path
a db needs to be built before it is searchable.

**Comment by nmquijada** [comment] 2020-09-08 15:25
Hi Clement,
It is looking for the blast-related commands. All of them might be well installed if you already set up the conda environment. I think the problem is the code I gave you.
Could you please try:
```
perl /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper.pl -d /home/ctsui/.conda/envs/tormes-1.2.0/CGE-modules/fimtyper/fimtyper_db -b /home/ctsui/.conda/envs/tormes-1.2.0/ -i E111_S15_contigs.filter.fasta -o E111_output -k 95.00 -l 0.80
```

**Comment by bhclement** [comment] 2020-09-08 15:34
Hello Narciso,

Thanks a lot. It works now. 
If I run Tormes again, the result of fimH will be included.

Also in principle, different software can be operated independently/separately within the Tormes conda env? if we have the correct code.

**Comment by nmquijada** [comment] 2020-09-08 15:55
Hi Clement,
Good that it worked!

Correct, if your run tormes again the fimH-typing results will be included.

Also yes regarding the software. Tormes is a pipeline that conducts a lot of steps by using different software, as you can see here: https://github.com/nmquijada/tormes#required-dependencies
In order to facilitate its usage, I made Tormes to work as a conda environment. This means that when you are installing the Tormes environment you are also installing all the software included in the link above. Therefore, you are able to use them all without the need of running the Tormes pipeline (although you need to activate the tormes environment first).

**Closed** 2020-09-16 08:54 UTC
Labels: bug, fimH-typing
